# Generated by Django 6.0.2 on 2026-02-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_disciplina', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ano_letivo', models.IntegerField()),
                ('serie', models.IntegerField()),
                ('secao', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lote_upload_id', models.CharField(blank=True, max_length=500, null=True)),
                ('probabilidade_evasao', models.FloatField(blank=True, db_index=True, null=True)),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='app.turma')),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma')),
            ],
            options={
                'verbose_name_plural': 'TurmaDisciplina',
            },
        ),
        migrations.AddField(
            model_name='turma',
            name='disciplinas',
            field=models.ManyToManyField(related_name='turmas', through='app.TurmaDisciplina', to='app.disciplina'),
        ),
        migrations.CreateModel(
            name='Desempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('situacao', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='app.aluno')),
                ('turma_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenhos', to='app.turmadisciplina')),
            ],
            options={
                'verbose_name_plural': 'Desempenhos',
            },
        ),
        migrations.AddConstraint(
            model_name='turmadisciplina',
            constraint=models.UniqueConstraint(fields=('turma', 'disciplina'), name='unique_turma_disciplina'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('ano_letivo', 'serie', 'secao'), name='unique_turma'),
        ),
        migrations.AddConstraint(
            model_name='desempenho',
            constraint=models.UniqueConstraint(fields=('aluno', 'turma_disciplina'), name='unique_aluno_turma_disciplina'),
        ),
    ]
