# Generated by Django 6.0 on 2025-12-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255, unique=True)),
                ('frequencia', models.FloatField()),
                ('nota_matematica', models.FloatField()),
                ('nota_portugues', models.FloatField()),
                ('lote_upload_id', models.CharField(max_length=900)),
                ('probabilidade_evasao', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'HistoricoAluno',
            },
        ),
    ]
