# Generated by Django 6.0 on 2025-12-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoaluno',
            name='id',
        ),
        migrations.AlterField(
            model_name='historicoaluno',
            name='matricula',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
