# Generated by Django 6.0 on 2025-12-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_historicoaluno_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survived', models.FloatField()),
                ('pclass', models.FloatField()),
                ('age', models.FloatField()),
                ('sibsp', models.FloatField()),
                ('parch', models.FloatField()),
                ('fare', models.FloatField()),
                ('sex_female', models.FloatField()),
                ('sex_male', models.FloatField()),
                ('embarked_c', models.FloatField()),
                ('embarked_q', models.FloatField()),
                ('embarked_s', models.FloatField()),
                ('survived_pred', models.FloatField(null=True)),
                ('lote_upload_id', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Passageiros',
            },
        ),
        migrations.AlterField(
            model_name='historicoaluno',
            name='lote_upload_id',
            field=models.CharField(max_length=500),
        ),
    ]
