# Generated by Django 6.0 on 2026-01-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_passageiro_alter_historicoaluno_lote_upload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoaluno',
            name='lote_upload_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicoaluno',
            name='probabilidade_evasao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
