# Generated by Django 6.0 on 2026-01-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_historicoaluno_lote_upload_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricoAluno',
            new_name='Aluno',
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name_plural': 'Alunos'},
        ),
    ]
